//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luat_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard_history
    {
        public string MaGiaoDich_CreditCard { get; set; }
        public string MaTheCreditCard { get; set; }
        public Nullable<int> SoTien { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string Status { get; set; }
    
        public virtual CreditCard CreditCard { get; set; }
    }
}
