//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luat_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.PhieuChuyenTiens = new HashSet<PhieuChuyenTien>();
            this.PhieuGuiTiens = new HashSet<PhieuGuiTien>();
            this.PhieuNopTienVaoSoTietKiems = new HashSet<PhieuNopTienVaoSoTietKiem>();
            this.PhieuRutTiens = new HashSet<PhieuRutTien>();
        }
    
        public string MaNhanVien { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> CMND { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<int> SDT { get; set; }
        public string ThuocChiNhanh { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string LoaiNhanVien { get; set; }
        public string Status { get; set; }
    
        public virtual ChiNhanhNganHang ChiNhanhNganHang { get; set; }
        public virtual LoaiNhanVien LoaiNhanVien1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuChuyenTien> PhieuChuyenTiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuGuiTien> PhieuGuiTiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNopTienVaoSoTietKiem> PhieuNopTienVaoSoTietKiems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuRutTien> PhieuRutTiens { get; set; }
    }
}
