//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.MM.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuGiaoDich
    {
        public string ID { get; set; }
        public string MaGiaoDich { get; set; }
        public string LoaiGiaoDich { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string Status { get; set; }
    
        public virtual LoaiGiaoDich LoaiGiaoDich1 { get; set; }
        public virtual PhieuChuyenTien PhieuChuyenTien { get; set; }
        public virtual PhieuGuiTien PhieuGuiTien { get; set; }
        public virtual PhieuNopTienVaoSoTietKiem PhieuNopTienVaoSoTietKiem { get; set; }
        public virtual PhieuRutTien PhieuRutTien { get; set; }
    }
}
