//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.MM.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThamSo
    {
        public string GiaTri { get; set; }
        public string Kieu { get; set; }
        public string MaThamSo { get; set; }
        public string TenThamSo { get; set; }
        public string Status { get; set; }
    }
}
