//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.MM.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruSoNganHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TruSoNganHang()
        {
            this.ChiNhanhNganHangs = new HashSet<ChiNhanhNganHang>();
        }
    
        public string MaTruSo { get; set; }
        public string TenTruSo { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiNhanhNganHang> ChiNhanhNganHangs { get; set; }
    }
}
